version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: auditocm_db
    restart: unless-stopped
    environment:
      MYSQL_DEFAULT_AUTHENTICATION_PLUGIN: mysql_native_password
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: auditocm
      MYSQL_USER: auditocm_user
      MYSQL_PASSWORD: auditocm_pass
    command: --local-infile=1
    volumes:
      - C:/GitHub/auditocm/files:/var/lib/mysql-files
    ports:
      - "3306:3306"

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: auditocm_backend
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: auditocm
      DB_USER: auditocm_user
      DB_PASS: auditocm_pass
    ports:
      - "8080:80"
    volumes:
        - ./apps/backend/public:/var/www/html:ro
        - ./apps/backend/src:/var/www/src:ro

volumes:
  db_data:
